const crypto = require("crypto");

function parseCookies(header) {
  return Object.fromEntries(
    (header || "")
      .split(";")
      .map((part) => part.trim())
      .filter(Boolean)
      .map((part) => {
        const index = part.indexOf("=");
        if (index === -1) return [part, ""];
        return [part.slice(0, index), decodeURIComponent(part.slice(index + 1))];
      })
  );
}

function htmlEscape(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function eventUrl(event) {
  if (event.rawUrl) return new URL(event.rawUrl);

  const host = event.headers.host || event.headers["x-forwarded-host"] || "safari-poc.netlify.app";
  const proto = event.headers["x-forwarded-proto"] || "https";
  const path = event.path || "/";
  const query = event.rawQuery ? `?${event.rawQuery}` : "";
  return new URL(`${proto}://${host}${path}${query}`);
}

exports.handler = async (event) => {
  const url = eventUrl(event);
  const cookies = parseCookies(event.headers.cookie);
  const existingId = cookies.safari_lock_poc;
  const visitId = existingId || crypto.randomBytes(8).toString("hex");

  const cookie = [
    `safari_lock_poc=${encodeURIComponent(visitId)}`,
    "Path=/",
    "SameSite=Lax",
    "Secure",
    "Max-Age=86400",
  ].join("; ");

  if (url.pathname === "/clear") {
    return {
      statusCode: 302,
      headers: {
        "Set-Cookie": "safari_lock_poc=deleted; Path=/; SameSite=Lax; Secure; Max-Age=0",
        "Location": "/?cleared=1",
        "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
      },
      body: "",
    };
  }

  const tokenUrl = new URL(url.toString());
  tokenUrl.pathname = "/";
  tokenUrl.searchParams.set("para", "poc");
  tokenUrl.searchParams.set("token", url.searchParams.get("token") || `demo-secret-${visitId}`);
  tokenUrl.searchParams.set("cachebust", Date.now().toString());

  const requestCookie = event.headers.cookie || "(none)";
  const requestSummary = [
    `${event.httpMethod || "GET"} ${url.pathname}${url.search}`,
    `Host: ${event.headers.host || ""}`,
    `Cookie: ${requestCookie}`,
    `User-Agent: ${event.headers["user-agent"] || ""}`,
  ].join("\n");

  return {
    statusCode: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Set-Cookie": cookie,
      "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
      "Pragma": "no-cache",
      "Expires": "0",
    },
    body: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Safari Lock Cookie PoC</title>
  <style>
    :root {
      color-scheme: light dark;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #f6f7f9;
      color: #17202a;
    }

    body {
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      padding: 24px;
      box-sizing: border-box;
    }

    main {
      width: min(720px, 100%);
      background: #ffffff;
      border: 1px solid #d9dee7;
      border-radius: 8px;
      padding: 24px;
      box-shadow: 0 14px 40px rgba(23, 32, 42, 0.08);
    }

    h1 {
      margin: 0 0 8px;
      font-size: 24px;
      line-height: 1.2;
    }

    p {
      line-height: 1.55;
    }

    code, pre {
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    }

    pre {
      white-space: pre-wrap;
      overflow-wrap: anywhere;
      background: #f0f3f7;
      border: 1px solid #d9dee7;
      border-radius: 6px;
      padding: 14px;
    }

    .actions {
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
      margin-top: 18px;
    }

    a, button {
      border: 1px solid #1f6feb;
      background: #1f6feb;
      color: #fff;
      border-radius: 6px;
      padding: 10px 14px;
      font: inherit;
      text-decoration: none;
      cursor: pointer;
    }

    a.secondary {
      background: transparent;
      color: #1f6feb;
    }

    @media (prefers-color-scheme: dark) {
      :root {
        background: #111418;
        color: #e8edf5;
      }

      main {
        background: #181d24;
        border-color: #303846;
      }

      pre {
        background: #111418;
        border-color: #303846;
      }
    }
  </style>
</head>
<body>
  <main>
    <h1>Safari Lock Cookie PoC</h1>
    <p>This response is generated by a Netlify Function. It sets <code>safari_lock_poc</code> with a real <code>Set-Cookie</code> header and sends <code>Cache-Control: no-store</code>.</p>

    <p><strong>Current request</strong></p>
    <pre>${htmlEscape(requestSummary)}</pre>

    <p><strong>PoC cookie value assigned by server</strong></p>
    <pre>safari_lock_poc=${htmlEscape(visitId)}</pre>

    <p><strong>Token URL for Safari restore testing</strong></p>
    <pre>${htmlEscape(tokenUrl.toString())}</pre>

    <div class="actions">
      <button type="button" onclick="location.reload()">Reload</button>
      <a class="secondary" href="${htmlEscape(tokenUrl.toString())}">Open token URL</a>
      <a class="secondary" href="/clear">Clear cookie</a>
    </div>
  </main>
</body>
</html>`,
  };
};
