[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/clear"
  to = "/.netlify/functions/poc"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/poc"
  status = 200
  force = true
